defaults: &defaults
  devise_pepper: a8c366b2da1581a9656ba09e990941469bac39ba82021a8b03ce5109669390fd5ef5a2422e5523e15cd4695bd3c47b82d7206ec6a31a12493d58bb382436dd1e
  devise_secret_key: 6e46e7fcdbeb2ef443296a8262a0934436c60da2006e2861ab1f57dac0d245fc1edc73b76cebf2dc1fcfce5ca066ee5aae47ddf418125b6e41ddbfdfbce08858
  secret_key_base: 1ee75d9dd7cd9755f2149e00a0dd923474d58b1dd13ca8c7e53f6be4e44fc94dc143dab73a2badfa943576aaa03e58509f7ce25836314f710031617306a6152e

secured: &secured
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  fog_directory: <%= ENV['S3_BUCKET'] %>
  fog_region: <%= ENV['FOG_REGION'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured
